version: "3.8"
services:
  web:
    build:
      context: docker
      dockerfile: nginx/Dockerfile
    ports:
      - "8808:80"
    volumes:
      - ./project:/app

  php-fpm:
    build:
      context: docker
      dockerfile: php-fpm/Dockerfile
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=API
    volumes:
      - ./project:/app

  php-cli:
    build:
      context: docker
      dockerfile: php-cli/Dockerfile
    environment:
      APP_ENV: local
      APP_DEBUG: 1
    volumes:
      - ./project:/app